alias l='ls --color=auto -ACFrt'
alias ll='ls --color=auto -AFlrt'
alias db=distrobox
alias dbl="distrobox list"
alias dbe="distrobox enter"
alias dbr="distrobox rm --force"
alias clams="distrobox enter CLAMS-devel"
alias rst="distrobox enter rstudio_bookworm"
alias emu="distrobox enter ExpMusTools-CUDA"

export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
export TZ=America/Los_Angeles

export PATH=$PATH:$HOME/.local/bin:$HOME/bin

. "$HOME/.cargo/env"
eval "$(starship init bash)"
